<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Cinema;

class CinemaSeeder extends Seeder
{
    public function run()
    {
        $cinemas = [
            [
                'city_id' => 1, 
                'name' => 'Adana Optimum Cinemaximum',
                'address' => 'Optimum AVM, Adana',
                'latitude' => 36.9914,
                'longitude' => 35.3308,
                'total_capacity' => 500,
                'phone' => '0322 123 45 67',
                'description' => 'Adana’nın en büyük sinemalarından biri.',
            ],
            [
                'city_id' => 1, 
                'name' => 'Cinemaximum M1 Adana',
                'address' => 'M1 Merkez Adana AVM, Adana',
                'latitude' => 36.9852,
                'longitude' => 35.3187,
                'total_capacity' => 450,
                'phone' => '0322 987 65 43',
                'description' => 'Adana’nın popüler sinemalarından.',
            ],
            [
                'city_id' => 2, 
                'name' => 'Adıyaman Park Cinemaximum',
                'address' => 'Adıyaman Park AVM, Adıyaman',
                'latitude' => 37.7644,
                'longitude' => 38.2785,
                'total_capacity' => 300,
                'phone' => '0416 987 65 43',
                'description' => 'Adıyaman’ın popüler sineması.',
            ],
            [
                'city_id' => 2, 
                'name' => 'Cinemaximum Adıyaman Merkez',
                'address' => 'Merkez, Adıyaman',
                'latitude' => 37.7612,
                'longitude' => 38.2756,
                'total_capacity' => 250,
                'phone' => '0416 123 45 67',
                'description' => 'Adıyaman’ın yeni sineması.',
            ],
            [
                'city_id' => 3, 
                'name' => 'Afium Outlet Cinemaximum',
                'address' => 'Afium Outlet AVM, Afyonkarahisar',
                'latitude' => 38.7516,
                'longitude' => 30.5518,
                'total_capacity' => 350,
                'phone' => '0272 876 54 32',
                'description' => 'Afyonkarahisar’ın modern sineması.',
            ],
            [
                'city_id' => 3, 
                'name' => 'Cinemaximum Park Afyon',
                'address' => 'Park Afyon AVM, Afyonkarahisar',
                'latitude' => 38.7498,
                'longitude' => 30.5489,
                'total_capacity' => 300,
                'phone' => '0272 543 21 09',
                'description' => 'Afyonkarahisar’ın yeni sineması.',
            ],
            [
                'city_id' => 4, 
                'name' => 'Ağrı Dağı Cinemaximum',
                'address' => 'Merkez, Ağrı',
                'latitude' => 39.7183,
                'longitude' => 43.0519,
                'total_capacity' => 200,
                'phone' => '0472 765 43 21',
                'description' => 'Ağrı’nın ilk ve tek sineması.',
            ],
            [
                'city_id' => 4, 
                'name' => 'Cinemaximum Ağrı AVM',
                'address' => 'Ağrı AVM, Ağrı',
                'latitude' => 39.7165,
                'longitude' => 43.0498,
                'total_capacity' => 180,
                'phone' => '0472 321 09 87',
                'description' => 'Ağrı’nın yeni sineması.',
            ],
            [
                'city_id' => 5, 
                'name' => 'Amasya Park Cinemaximum',
                'address' => 'Amasya Park AVM, Amasya',
                'latitude' => 40.6517,
                'longitude' => 35.8398,
                'total_capacity' => 250,
                'phone' => '0358 654 32 10',
                'description' => 'Amasya’nın yeni sineması.',
            ],
            [
                'city_id' => 5, 
                'name' => 'Cinemaximum Amasya Merkez',
                'address' => 'Merkez, Amasya',
                'latitude' => 40.6498,
                'longitude' => 35.8379,
                'total_capacity' => 220,
                'phone' => '0358 123 45 67',
                'description' => 'Amasya’nın popüler sineması.',
            ],
            [
                'city_id' => 6, 
                'name' => 'Ankamall Cinemaximum',
                'address' => 'Ankamall AVM, Ankara',
                'latitude' => 39.9334,
                'longitude' => 32.8597,
                'total_capacity' => 700,
                'phone' => '0312 543 21 09',
                'description' => 'Ankara’nın en büyük sinemalarından biri.',
            ],
            [
                'city_id' => 6,
                'name' => 'Cinemaximum Kentpark',
                'address' => 'Kentpark AVM, Ankara',
                'latitude' => 39.9287,
                'longitude' => 32.8546,
                'total_capacity' => 650,
                'phone' => '0312 987 65 43',
                'description' => 'Ankara’nın popüler sinemalarından.',
            ],
            [
                'city_id' => 7, 
                'name' => 'Antalya Migros Cinemaximum',
                'address' => 'Migros AVM, Antalya',
                'latitude' => 36.8856,
                'longitude' => 30.6974,
                'total_capacity' => 600,
                'phone' => '0242 432 10 98',
                'description' => 'Antalya’nın popüler sinemalarından biri.',
            ],
            [
                'city_id' => 7, 
                'name' => 'Cinemaximum TerraCity',
                'address' => 'TerraCity AVM, Antalya',
                'latitude' => 36.8823,
                'longitude' => 30.6941,
                'total_capacity' => 550,
                'phone' => '0242 123 45 67',
                'description' => 'Antalya’nın lüks sinemalarından.',
            ],
            [
                'city_id' => 8, 
                'name' => 'Cinemaximum Hopa',
                'address' => 'Hopa, Artvin',
                'latitude' => 41.3812,
                'longitude' => 41.4198,
                'total_capacity' => 120,
                'phone' => '0466 987 65 43',
                'description' => 'Artvin’in Hopa ilçesindeki sineması.',
            ],
            [
                'city_id' => 9,
                'name' => 'Aydın Cinemaximum Merkez',
                'address' => 'Merkez, Aydın',
                'latitude' => 37.8467,
                'longitude' => 27.8409,
                'total_capacity' => 400,
                'phone' => '0256 543 21 09',
                'description' => 'Aydın’ın merkezindeki sineması.',
            ],
            [
                'city_id' => 9, 
                'name' => 'Cinemaximum Kuşadası',
                'address' => 'Kuşadası, Aydın',
                'latitude' => 37.8654,
                'longitude' => 27.2618,
                'total_capacity' => 350,
                'phone' => '0256 123 45 67',
                'description' => 'Aydın’ın Kuşadası ilçesindeki sineması.',
            ],
            [
                'city_id' => 10, 
                'name' => 'Balıkesir Cinemaximum Merkez',
                'address' => 'Merkez, Balıkesir',
                'latitude' => 39.6465,
                'longitude' => 27.8897,
                'total_capacity' => 380,
                'phone' => '0266 432 10 98',
                'description' => 'Balıkesir’in merkezindeki sineması.',
            ],
            [
                'city_id' => 10, 
                'name' => 'Cinemaximum Edremit',
                'address' => 'Edremit, Balıkesir',
                'latitude' => 39.5987,
                'longitude' => 27.0012,
                'total_capacity' => 330,
                'phone' => '0266 987 65 43',
                'description' => 'Balıkesir’in Edremit ilçesindeki sineması.',
            ],
            [
                'city_id' => 11,
                'name' => 'Bilecik Cinemaximum Merkez',
                'address' => 'Merkez, Bilecik',
                'latitude' => 40.1476,
                'longitude' => 29.9863,
                'total_capacity' => 200,
                'phone' => '0228 321 09 87',
                'description' => 'Bilecik’in merkezindeki sineması.',
            ],
            [
                'city_id' => 11,
                'name' => 'Cinemaximum Bozüyük',
                'address' => 'Bozüyük, Bilecik',
                'latitude' => 39.8456,
                'longitude' => 30.1023,
                'total_capacity' => 180,
                'phone' => '0228 987 65 43',
                'description' => 'Bilecik’in Bozüyük ilçesindeki sineması.',
            ],
            [
                'city_id' => 12,
                'name' => 'Bingöl Park Cinemaximum',
                'address' => 'Bingöl Park AVM, Bingöl',
                'latitude' => 38.8876,
                'longitude' => 40.5012,
                'total_capacity' => 220,
                'phone' => '0426 123 45 67',
                'description' => 'Bingöl’ün popüler sineması.',
            ],
            [
                'city_id' => 12,
                'name' => 'Cinemaximum Bingöl Merkez',
                'address' => 'Merkez, Bingöl',
                'latitude' => 38.8854,
                'longitude' => 40.4987,
                'total_capacity' => 200,
                'phone' => '0426 543 21 09',
                'description' => 'Bingöl’ün yeni sineması.',
            ],
            [
                'city_id' => 13,
                'name' => 'Bitlis Park Cinemaximum',
                'address' => 'Bitlis Park AVM, Bitlis',
                'latitude' => 38.3976,
                'longitude' => 42.1123,
                'total_capacity' => 180,
                'phone' => '0434 987 65 43',
                'description' => 'Bitlis’in popüler sineması.',
            ],
            [
                'city_id' => 13,
                'name' => 'Cinemaximum Tatvan',
                'address' => 'Tatvan, Bitlis',
                'latitude' => 38.5012,
                'longitude' => 42.2654,
                'total_capacity' => 160,
                'phone' => '0434 321 09 87',
                'description' => 'Bitlis’in Tatvan ilçesindeki sineması.',
            ],
            [
                'city_id' => 14,
                'name' => 'Bolu 14 Burda Cinemaximum',
                'address' => '14 Burda AVM, Bolu',
                'latitude' => 40.7321,
                'longitude' => 31.6098,
                'total_capacity' => 300,
                'phone' => '0374 123 45 67',
                'description' => 'Bolu’nun modern sineması.',
            ],
            [
                'city_id' => 14,
                'name' => 'Cinemaximum Bolu Merkez',
                'address' => 'Merkez, Bolu',
                'latitude' => 40.7300,
                'longitude' => 31.6076,
                'total_capacity' => 280,
                'phone' => '0374 543 21 09',
                'description' => 'Bolu’nun yeni sineması.',
            ],
            [
                'city_id' => 15,
                'name' => 'Burdur Park Cinemaximum',
                'address' => 'Burdur Park AVM, Burdur',
                'latitude' => 37.7298,
                'longitude' => 30.2987,
                'total_capacity' => 250,
                'phone' => '0248 987 65 43',
                'description' => 'Burdur’un popüler sineması.',
            ],
            [
                'city_id' => 15,
                'name' => 'Cinemaximum Burdur Merkez',
                'address' => 'Merkez, Burdur',
                'latitude' => 37.7276,
                'longitude' => 30.2965,
                'total_capacity' => 230,
                'phone' => '0248 321 09 87',
                'description' => 'Burdur’un yeni sineması.',
            ],
            [
                'city_id' => 16,
                'name' => 'CarrefourSA Cinemaximum Bursa',
                'address' => 'CarrefourSA AVM, Bursa',
                'latitude' => 40.1876,
                'longitude' => 29.0654,
                'total_capacity' => 400,
                'phone' => '0224 123 45 67',
                'description' => 'Bursa’nın popüler sinemalarından.',
            ],
            [
                'city_id' => 16,
                'name' => 'Cinemaximum Kent Meydanı Bursa',
                'address' => 'Kent Meydanı AVM, Bursa',
                'latitude' => 40.1854,
                'longitude' => 29.0632,
                'total_capacity' => 380,
                'phone' => '0224 543 21 09',
                'description' => 'Bursa’nın modern sinemalarından.',
            ],
            [
                'city_id' => 17,
                'name' => 'Çanakkale 17 Burda Cinemaximum',
                'address' => '17 Burda AVM, Çanakkale',
                'latitude' => 40.1576,
                'longitude' => 26.4123,
                'total_capacity' => 350,
                'phone' => '0286 987 65 43',
                'description' => 'Çanakkale’nin yeni sineması.',
            ],
            [
                'city_id' => 17,
                'name' => 'Cinemaximum Çanakkale Merkez',
                'address' => 'Merkez, Çanakkale',
                'latitude' => 40.1554,
                'longitude' => 26.4101,
                'total_capacity' => 330,
                'phone' => '0286 321 09 87',
                'description' => 'Çanakkale’nin popüler sineması.',
            ],
            [
                'city_id' => 18,
                'name' => 'Cinemaximum Çankırı Merkez',
                'address' => 'Merkez, Çankırı',
                'latitude' => 40.6054,
                'longitude' => 33.6212,
                'total_capacity' => 260,
                'phone' => '0376 543 21 09',
                'description' => 'Çankırı’nın yeni sineması.',
            ],
            [
                'city_id' => 19,
                'name' => 'Çorum AHL Park Cinemaximum',
                'address' => 'AHL Park AVM, Çorum',
                'latitude' => 40.5476,
                'longitude' => 34.9567,
                'total_capacity' => 320,
                'phone' => '0364 987 65 43',
                'description' => 'Çorum’un popüler sinemalarından.',
            ],
            [
                'city_id' => 19,
                'name' => 'Cinemaximum Çorum Merkez',
                'address' => 'Merkez, Çorum',
                'latitude' => 40.5454,
                'longitude' => 34.9545,
                'total_capacity' => 300,
                'phone' => '0364 321 09 87',
                'description' => 'Çorum’un yeni sineması.',
            ],
            [
                'city_id' => 20,
                'name' => 'Denizli Teras Park Cinemaximum',
                'address' => 'Teras Park AVM, Denizli',
                'latitude' => 37.7776,
                'longitude' => 29.0876,
                'total_capacity' => 380,
                'phone' => '0258 123 45 67',
                'description' => 'Denizli’nin popüler sinemalarından.',
            ],
            [
                'city_id' => 20,
                'name' => 'Cinemaximum Forum Denizli',
                'address' => 'Forum Denizli AVM, Denizli',
                'latitude' => 37.7754,
                'longitude' => 29.0854,
                'total_capacity' => 360,
                'phone' => '0258 543 21 09',
                'description' => 'Denizli’nin modern sineması.',
            ],
            [
                'city_id' => 21,
                'name' => 'Diyarbakır Ceylan Karavil Park Cinemaximum',
                'address' => 'Ceylan Karavil Park AVM, Diyarbakır',
                'latitude' => 37.9176,
                'longitude' => 40.2345,
                'total_capacity' => 400,
                'phone' => '0412 123 45 67',
                'description' => 'Diyarbakır’ın popüler sinemalarından.',
            ],
            [
                'city_id' => 21,
                'name' => 'Cinemaximum Forum Diyarbakır',
                'address' => 'Forum Diyarbakır AVM, Diyarbakır',
                'latitude' => 37.9154,
                'longitude' => 40.2323,
                'total_capacity' => 380,
                'phone' => '0412 543 21 09',
                'description' => 'Diyarbakır’ın modern sineması.',
            ],
            [
                'city_id' => 22,
                'name' => 'Edirne Erasta Cinemaximum',
                'address' => 'Erasta AVM, Edirne',
                'latitude' => 41.6776,
                'longitude' => 26.5567,
                'total_capacity' => 350,
                'phone' => '0284 987 65 43',
                'description' => 'Edirne’nin yeni sineması.',
            ],
            [
                'city_id' => 22,
                'name' => 'Cinemaximum Edirne Merkez',
                'address' => 'Merkez, Edirne',
                'latitude' => 41.6754,
                'longitude' => 26.5545,
                'total_capacity' => 330,
                'phone' => '0284 321 09 87',
                'description' => 'Edirne’nin popüler sineması.',
            ],
            [
                'city_id' => 23,
                'name' => 'Elazığ Park 23 Cinemaximum',
                'address' => 'Park 23 AVM, Elazığ',
                'latitude' => 38.6776,
                'longitude' => 39.2123,
                'total_capacity' => 300,
                'phone' => '0424 123 45 67',
                'description' => 'Elazığ’ın popüler sineması.',
            ],
            [
                'city_id' => 23,
                'name' => 'Cinemaximum Elazığ Merkez',
                'address' => 'Merkez, Elazığ',
                'latitude' => 38.6754,
                'longitude' => 39.2101,
                'total_capacity' => 280,
                'phone' => '0424 543 21 09',
                'description' => 'Elazığ’ın yeni sineması.',
            ],
            [
                'city_id' => 24,
                'name' => 'Erzincan Park Cinemaximum',
                'address' => 'Erzincan Park AVM, Erzincan',
                'latitude' => 39.7476,
                'longitude' => 39.4987,
                'total_capacity' => 250,
                'phone' => '0446 987 65 43',
                'description' => 'Erzincan’ın popüler sineması.',
            ],
            [
                'city_id' => 24,
                'name' => 'Cinemaximum Erzincan Merkez',
                'address' => 'Merkez, Erzincan',
                'latitude' => 39.7454,
                'longitude' => 39.4965,
                'total_capacity' => 230,
                'phone' => '0446 321 09 87',
                'description' => 'Erzincan’ın yeni sineması.',
            ],
            [
                'city_id' => 25,
                'name' => 'Erzurum MNG Cinemaximum',
                'address' => 'MNG AVM, Erzurum',
                'latitude' => 39.9076,
                'longitude' => 41.2754,
                'total_capacity' => 380,
                'phone' => '0442 123 45 67',
                'description' => 'Erzurum’un popüler sinemalarından.',
            ],
            [
                'city_id' => 25,
                'name' => 'Cinemaximum Palandöken Erzurum',
                'address' => 'Palandöken, Erzurum',
                'latitude' => 39.9054,
                'longitude' => 41.2732,
                'total_capacity' => 360,
                'phone' => '0442 543 21 09',
                'description' => 'Erzurum’un modern sineması.',
            ],
            [
                'city_id' => 26,
                'name' => 'Eskişehir Espark Cinemaximum',
                'address' => 'Espark AVM, Eskişehir',
                'latitude' => 39.7676,
                'longitude' => 30.5265,
                'total_capacity' => 400,
                'phone' => '0222 987 65 43',
                'description' => 'Eskişehir’in popüler sinemalarından.',
            ],
            [
                'city_id' => 26,
                'name' => 'Cinemaximum Kanatlı AVM',
                'address' => 'Kanatlı AVM, Eskişehir',
                'latitude' => 39.7654,
                'longitude' => 30.5243,
                'total_capacity' => 380,
                'phone' => '0222 321 09 87',
                'description' => 'Eskişehir’in modern sineması.',
            ],
            [
                'city_id' => 27,
                'name' => 'Gaziantep Sanko Park Cinemaximum',
                'address' => 'Sanko Park AVM, Gaziantep',
                'latitude' => 37.0676,
                'longitude' => 37.3876,
                'total_capacity' => 450,
                'phone' => '0342 123 45 67',
                'description' => 'Gaziantep’in popüler sinemalarından.',
            ],
            [
                'city_id' => 27,
                'name' => 'Cinemaximum Forum Gaziantep',
                'address' => 'Forum Gaziantep AVM, Gaziantep',
                'latitude' => 37.0654,
                'longitude' => 37.3854,
                'total_capacity' => 430,
                'phone' => '0342 543 21 09',
                'description' => 'Gaziantep’in modern sineması.',
            ],
            [
                'city_id' => 28,
                'name' => 'Cinemaximum Giresun Merkez',
                'address' => 'Merkez, Giresun',
                'latitude' => 40.9154,
                'longitude' => 38.3965,
                'total_capacity' => 280,
                'phone' => '0454 543 21 09',
                'description' => 'Giresun’un yeni sineması.',
            ],
            [
                'city_id' => 29,
                'name' => 'Gümüşhane Park Cinemaximum',
                'address' => 'Gümüşhane Park AVM, Gümüşhane',
                'latitude' => 40.4576,
                'longitude' => 39.4876,
                'total_capacity' => 250,
                'phone' => '0456 123 45 67',
                'description' => 'Gümüşhane’nin popüler sineması.',
            ],
            [
                'city_id' => 29,
                'name' => 'Cinemaximum Gümüşhane Merkez',
                'address' => 'Merkez, Gümüşhane',
                'latitude' => 40.4554,
                'longitude' => 39.4854,
                'total_capacity' => 230,
                'phone' => '0456 543 21 09',
                'description' => 'Gümüşhane’nin yeni sineması.',
            ],
            [
                'city_id' => 30,
                'name' => 'Hakkari Park Cinemaximum',
                'address' => 'Hakkari Park AVM, Hakkari',
                'latitude' => 37.5776,
                'longitude' => 43.7376,
                'total_capacity' => 200,
                'phone' => '0438 987 65 43',
                'description' => 'Hakkari’nin popüler sineması.',
            ],
            [
                'city_id' => 30,
                'name' => 'Cinemaximum Yüksekova',
                'address' => 'Yüksekova, Hakkari',
                'latitude' => 37.5854,
                'longitude' => 44.2754,
                'total_capacity' => 180,
                'phone' => '0438 321 09 87',
                'description' => 'Hakkari’nin Yüksekova ilçesindeki sineması.',
            ],
            [
                'city_id' => 31,
                'name' => 'Hatay Primemall Cinemaximum',
                'address' => 'Primemall AVM, Hatay',
                'latitude' => 36.2076,
                'longitude' => 36.1576,
                'total_capacity' => 400,
                'phone' => '0326 123 45 67',
                'description' => 'Hatay’ın popüler sinemalarından.',
            ],
            [
                'city_id' => 31,
                'name' => 'Cinemaximum İskenderun',
                'address' => 'İskenderun, Hatay',
                'latitude' => 36.5876,
                'longitude' => 36.1776,
                'total_capacity' => 380,
                'phone' => '0326 543 21 09',
                'description' => 'Hatay’ın İskenderun ilçesindeki sineması.',
            ],
            [
                'city_id' => 32,
                'name' => 'Isparta Iyaşpark Cinemaximum',
                'address' => 'Iyaşpark AVM, Isparta',
                'latitude' => 37.7676,
                'longitude' => 30.5576,
                'total_capacity' => 350,
                'phone' => '0246 987 65 43',
                'description' => 'Isparta’nın popüler sineması.',
            ],
            [
                'city_id' => 32,
                'name' => 'Cinemaximum Isparta Merkez',
                'address' => 'Merkez, Isparta',
                'latitude' => 37.7654,
                'longitude' => 30.5554,
                'total_capacity' => 330,
                'phone' => '0246 321 09 87',
                'description' => 'Isparta’nın yeni sineması.',
            ],
            [
                'city_id' => 33,
                'name' => 'Mersin Forum Cinemaximum',
                'address' => 'Forum AVM, Mersin',
                'latitude' => 36.8076,
                'longitude' => 34.6376,
                'total_capacity' => 450,
                'phone' => '0324 123 45 67',
                'description' => 'Mersin’in popüler sinemalarından.',
            ],
            [
                'city_id' => 33,
                'name' => 'Cinemaximum Marina Mersin',
                'address' => 'Marina AVM, Mersin',
                'latitude' => 36.8054,
                'longitude' => 34.6354,
                'total_capacity' => 430,
                'phone' => '0324 543 21 09',
                'description' => 'Mersin’in modern sineması.',
            ],
            [
                'city_id' => 34,
                'name' => 'İstanbul İstinyePark Cinemaximum',
                'address' => 'İstinyePark AVM, İstanbul',
                'latitude' => 41.1076,
                'longitude' => 29.0376,
                'total_capacity' => 800,
                'phone' => '0212 987 65 43',
                'description' => 'İstanbul’un lüks sinemalarından.',
            ],
            [
                'city_id' => 34,
                'name' => 'Cinemaximum Zorlu Center',
                'address' => 'Zorlu Center AVM, İstanbul',
                'latitude' => 41.0676,
                'longitude' => 29.0176,
                'total_capacity' => 750,
                'phone' => '0212 321 09 87',
                'description' => 'İstanbul’un popüler sinemalarından.',
            ],
            [
                'city_id' => 35,
                'name' => 'İzmir Optimum Cinemaximum',
                'address' => 'Optimum AVM, İzmir',
                'latitude' => 38.4176,
                'longitude' => 27.1376,
                'total_capacity' => 500,
                'phone' => '0232 123 45 67',
                'description' => 'İzmir’in popüler sinemalarından.',
            ],
            [
                'city_id' => 35,
                'name' => 'Cinemaximum Forum Bornova',
                'address' => 'Forum Bornova AVM, İzmir',
                'latitude' => 38.4576,
                'longitude' => 27.2176,
                'total_capacity' => 480,
                'phone' => '0232 543 21 09',
                'description' => 'İzmir’in modern sineması.',
            ],
            [
                'city_id' => 36,
                'name' => 'Kars Cinemaximum Merkez',
                'address' => 'Merkez, Kars',
                'latitude' => 40.6076,
                'longitude' => 43.1076,
                'total_capacity' => 250,
                'phone' => '0474 987 65 43',
                'description' => 'Kars’ın popüler sineması.',
            ],
            [
                'city_id' => 36,
                'name' => 'Cinemaximum Kağızman',
                'address' => 'Kağızman, Kars',
                'latitude' => 40.2376,
                'longitude' => 43.3076,
                'total_capacity' => 230,
                'phone' => '0474 321 09 87',
                'description' => 'Kars’ın Kağızman ilçesindeki sineması.',
            ],
            [
                'city_id' => 37,
                'name' => 'Kastamonu Park Cinemaximum',
                'address' => 'Kastamonu Park AVM, Kastamonu',
                'latitude' => 41.3776,
                'longitude' => 33.6676,
                'total_capacity' => 300,
                'phone' => '0366 123 45 67',
                'description' => 'Kastamonu’nun popüler sineması.',
            ],
            [
                'city_id' => 37,
                'name' => 'Cinemaximum Kastamonu Merkez',
                'address' => 'Merkez, Kastamonu',
                'latitude' => 41.3754,
                'longitude' => 33.6654,
                'total_capacity' => 280,
                'phone' => '0366 543 21 09',
                'description' => 'Kastamonu’nun yeni sineması.',
            ],
            [
                'city_id' => 38,
                'name' => 'Kayseri Forum Cinemaximum',
                'address' => 'Forum AVM, Kayseri',
                'latitude' => 38.7276,
                'longitude' => 35.4876,
                'total_capacity' => 400,
                'phone' => '0352 987 65 43',
                'description' => 'Kayseri’nin popüler sinemalarından.',
            ],
            [
                'city_id' => 38,
                'name' => 'Cinemaximum Park Kayseri',
                'address' => 'Park AVM, Kayseri',
                'latitude' => 38.7254,
                'longitude' => 35.4854,
                'total_capacity' => 380,
                'phone' => '0352 321 09 87',
                'description' => 'Kayseri’nin modern sineması.',
            ],
            [
                'city_id' => 39,
                'name' => 'Kırklareli Cinemaximum Merkez',
                'address' => 'Merkez, Kırklareli',
                'latitude' => 41.7376,
                'longitude' => 27.2276,
                'total_capacity' => 320,
                'phone' => '0288 123 45 67',
                'description' => 'Kırklareli’nin popüler sineması.',
            ],
            [
                'city_id' => 39,
                'name' => 'Cinemaximum Lüleburgaz',
                'address' => 'Lüleburgaz, Kırklareli',
                'latitude' => 41.4076,
                'longitude' => 27.2276,
                'total_capacity' => 300,
                'phone' => '0288 543 21 09',
                'description' => 'Kırklareli’nin Lüleburgaz ilçesindeki sineması.',
            ],
            [
                'city_id' => 40,
                'name' => 'Kırşehir Park Cinemaximum',
                'address' => 'Kırşehir Park AVM, Kırşehir',
                'latitude' => 39.1476,
                'longitude' => 34.1676,
                'total_capacity' => 280,
                'phone' => '0386 987 65 43',
                'description' => 'Kırşehir’in popüler sineması.',
            ],
            [
                'city_id' => 40,
                'name' => 'Cinemaximum Kırşehir Merkez',
                'address' => 'Merkez, Kırşehir',
                'latitude' => 39.1454,
                'longitude' => 34.1654,
                'total_capacity' => 260,
                'phone' => '0386 321 09 87',
                'description' => 'Kırşehir’in yeni sineması.',
            ],
            [
                'city_id' => 41,
                'name' => 'Kocaeli Symbol Cinemaximum',
                'address' => 'Symbol AVM, Kocaeli',
                'latitude' => 40.7676,
                'longitude' => 29.9176,
                'total_capacity' => 420,
                'phone' => '0262 123 45 67',
                'description' => 'Kocaeli’nin popüler sinemalarından.',
            ],
            [
                'city_id' => 41,
                'name' => 'Cinemaximum İzmit',
                'address' => 'İzmit, Kocaeli',
                'latitude' => 40.7654,
                'longitude' => 29.9154,
                'total_capacity' => 400,
                'phone' => '0262 543 21 09',
                'description' => 'Kocaeli’nin İzmit ilçesindeki sineması.',
            ],
            [
                'city_id' => 42,
                'name' => 'Konya Kent Plaza Cinemaximum',
                'address' => 'Kent Plaza AVM, Konya',
                'latitude' => 37.8776,
                'longitude' => 32.4876,
                'total_capacity' => 450,
                'phone' => '0332 987 65 43',
                'description' => 'Konya’nın popüler sinemalarından.',
            ],
            [
                'city_id' => 42,
                'name' => 'Cinemaximum Kulesite Konya',
                'address' => 'Kulesite AVM, Konya',
                'latitude' => 37.8754,
                'longitude' => 32.4854,
                'total_capacity' => 430,
                'phone' => '0332 321 09 87',
                'description' => 'Konya’nın modern sineması.',
            ],
            [
                'city_id' => 43,
                'name' => 'Kütahya Sera AVM Cinemaximum',
                'address' => 'Sera AVM, Kütahya',
                'latitude' => 39.4276,
                'longitude' => 29.9876,
                'total_capacity' => 330,
                'phone' => '0274 123 45 67',
                'description' => 'Kütahya’nın popüler sineması.',
            ],
            [
                'city_id' => 43,
                'name' => 'Cinemaximum Kütahya Merkez',
                'address' => 'Merkez, Kütahya',
                'latitude' => 39.4254,
                'longitude' => 29.9854,
                'total_capacity' => 310,
                'phone' => '0274 543 21 09',
                'description' => 'Kütahya’nın yeni sineması.',
            ],
            [
                'city_id' => 44,
                'name' => 'Malatya Park Cinemaximum',
                'address' => 'Malatya Park AVM, Malatya',
                'latitude' => 38.3576,
                'longitude' => 38.3176,
                'total_capacity' => 380,
                'phone' => '0422 987 65 43',
                'description' => 'Malatya’nın popüler sineması.',
            ],
            [
                'city_id' => 44,
                'name' => 'Cinemaximum Malatya Merkez',
                'address' => 'Merkez, Malatya',
                'latitude' => 38.3554,
                'longitude' => 38.3154,
                'total_capacity' => 360,
                'phone' => '0422 321 09 87',
                'description' => 'Malatya’nın yeni sineması.',
            ],
            [
                'city_id' => 45,
                'name' => 'Manisa Magnesia Cinemaximum',
                'address' => 'Magnesia AVM, Manisa',
                'latitude' => 38.6276,
                'longitude' => 27.4276,
                'total_capacity' => 400,
                'phone' => '0236 123 45 67',
                'description' => 'Manisa’nın popüler sineması.',
            ],
            [
                'city_id' => 45,
                'name' => 'Cinemaximum Manisa Merkez',
                'address' => 'Merkez, Manisa',
                'latitude' => 38.6254,
                'longitude' => 27.4254,
                'total_capacity' => 380,
                'phone' => '0236 543 21 09',
                'description' => 'Manisa’nın yeni sineması.',
            ],
            [
                'city_id' => 46,
                'name' => 'Kahramanmaraş Piazza Cinemaximum',
                'address' => 'Piazza AVM, Kahramanmaraş',
                'latitude' => 37.5776,
                'longitude' => 36.9376,
                'total_capacity' => 420,
                'phone' => '0344 123 45 67',
                'description' => 'Kahramanmaraş’ın popüler sinemalarından.',
            ],
            [
                'city_id' => 46,
                'name' => 'Cinemaximum Kahramanmaraş Merkez',
                'address' => 'Merkez, Kahramanmaraş',
                'latitude' => 37.5754,
                'longitude' => 36.9354,
                'total_capacity' => 400,
                'phone' => '0344 543 21 09',
                'description' => 'Kahramanmaraş’ın yeni sineması.',
            ],
            [
                'city_id' => 47,
                'name' => 'Mardin Movapark Cinemaximum',
                'address' => 'Movapark AVM, Mardin',
                'latitude' => 37.3176,
                'longitude' => 40.7376,
                'total_capacity' => 350,
                'phone' => '0482 987 65 43',
                'description' => 'Mardin’in popüler sineması.',
            ],
            [
                'city_id' => 47,
                'name' => 'Cinemaximum Mardin Merkez',
                'address' => 'Merkez, Mardin',
                'latitude' => 37.3154,
                'longitude' => 40.7354,
                'total_capacity' => 330,
                'phone' => '0482 321 09 87',
                'description' => 'Mardin’in yeni sineması.',
            ],
            [
                'city_id' => 48,
                'name' => 'Muğla Cinemaximum Merkez',
                'address' => 'Merkez, Muğla',
                'latitude' => 37.2176,
                'longitude' => 28.3676,
                'total_capacity' => 380,
                'phone' => '0252 123 45 67',
                'description' => 'Muğla’nın popüler sineması.',
            ],
            [
                'city_id' => 48,
                'name' => 'Cinemaximum Bodrum',
                'address' => 'Bodrum, Muğla',
                'latitude' => 37.0376,
                'longitude' => 27.4276,
                'total_capacity' => 360,
                'phone' => '0252 543 21 09',
                'description' => 'Muğla’nın Bodrum ilçesindeki sineması.',
            ],
            [
                'city_id' => 49,
                'name' => 'Muş Park Cinemaximum',
                'address' => 'Muş Park AVM, Muş',
                'latitude' => 38.7376,
                'longitude' => 41.4876,
                'total_capacity' => 300,
                'phone' => '0436 987 65 43',
                'description' => 'Muş’un popüler sineması.',
            ],
            [
                'city_id' => 49,
                'name' => 'Cinemaximum Muş Merkez',
                'address' => 'Merkez, Muş',
                'latitude' => 38.7354,
                'longitude' => 41.4854,
                'total_capacity' => 280,
                'phone' => '0436 321 09 87',
                'description' => 'Muş’un yeni sineması.',
            ],
            [
                'city_id' => 50,
                'name' => 'Nevşehir Forum Kapadokya Cinemaximum',
                'address' => 'Forum Kapadokya AVM, Nevşehir',
                'latitude' => 38.6276,
                'longitude' => 34.8276,
                'total_capacity' => 330,
                'phone' => '0384 123 45 67',
                'description' => 'Nevşehir’in popüler sineması.',
            ],
            [
                'city_id' => 50,
                'name' => 'Cinemaximum Nevşehir Merkez',
                'address' => 'Merkez, Nevşehir',
                'latitude' => 38.6254,
                'longitude' => 34.8254,
                'total_capacity' => 310,
                'phone' => '0384 543 21 09',
                'description' => 'Nevşehir’in yeni sineması.',
            ],
            [
                'city_id' => 51,
                'name' => 'Niğde Park Cinemaximum',
                'address' => 'Niğde Park AVM, Niğde',
                'latitude' => 37.9676,
                'longitude' => 34.6876,
                'total_capacity' => 280,
                'phone' => '0388 987 65 43',
                'description' => 'Niğde’nin popüler sineması.',
            ],
            [
                'city_id' => 51,
                'name' => 'Cinemaximum Niğde Merkez',
                'address' => 'Merkez, Niğde',
                'latitude' => 37.9654,
                'longitude' => 34.6854,
                'total_capacity' => 260,
                'phone' => '0388 321 09 87',
                'description' => 'Niğde’nin yeni sineması.',
            ],
            [
                'city_id' => 52,
                'name' => 'Ordu Novada Cinemaximum',
                'address' => 'Novada AVM, Ordu',
                'latitude' => 40.9876,
                'longitude' => 37.8876,
                'total_capacity' => 350,
                'phone' => '0452 123 45 67',
                'description' => 'Ordu’nun popüler sineması.',
            ],
            [
                'city_id' => 52,
                'name' => 'Cinemaximum Ordu Merkez',
                'address' => 'Merkez, Ordu',
                'latitude' => 40.9854,
                'longitude' => 37.8854,
                'total_capacity' => 330,
                'phone' => '0452 543 21 09',
                'description' => 'Ordu’nun yeni sineması.',
            ],
            [
                'city_id' => 53,
                'name' => 'Rize Cinemaximum Merkez',
                'address' => 'Merkez, Rize',
                'latitude' => 41.0276,
                'longitude' => 40.5276,
                'total_capacity' => 300,
                'phone' => '0464 987 65 43',
                'description' => 'Rize’nin popüler sineması.',
            ],
            [
                'city_id' => 53,
                'name' => 'Cinemaximum Çayeli',
                'address' => 'Çayeli, Rize',
                'latitude' => 41.0776,
                'longitude' => 40.7376,
                'total_capacity' => 280,
                'phone' => '0464 321 09 87',
                'description' => 'Rize’nin Çayeli ilçesindeki sineması.',
            ],
            [
                'city_id' => 54,
                'name' => 'Sakarya Serdivan Cinemaximum',
                'address' => 'Serdivan AVM, Sakarya',
                'latitude' => 40.7876,
                'longitude' => 30.4076,
                'total_capacity' => 400,
                'phone' => '0264 123 45 67',
                'description' => 'Sakarya’nın popüler sineması.',
            ],
            [
                'city_id' => 54,
                'name' => 'Cinemaximum Adapazarı',
                'address' => 'Adapazarı, Sakarya',
                'latitude' => 40.7854,
                'longitude' => 30.4054,
                'total_capacity' => 380,
                'phone' => '0264 543 21 09',
                'description' => 'Sakarya’nın Adapazarı ilçesindeki sineması.',
            ],
            [
                'city_id' => 55,
                'name' => 'Samsun Piazza Cinemaximum',
                'address' => 'Piazza AVM, Samsun',
                'latitude' => 41.2876,
                'longitude' => 36.3376,
                'total_capacity' => 420,
                'phone' => '0362 987 65 43',
                'description' => 'Samsun’un popüler sinemalarından.',
            ],
            [
                'city_id' => 55,
                'name' => 'Cinemaximum Bulvar AVM',
                'address' => 'Bulvar AVM, Samsun',
                'latitude' => 41.2854,
                'longitude' => 36.3354,
                'total_capacity' => 400,
                'phone' => '0362 321 09 87',
                'description' => 'Samsun’un modern sineması.',
            ],
            [
                'city_id' => 56,
                'name' => 'Siirt Park Cinemaximum',
                'address' => 'Siirt Park AVM, Siirt',
                'latitude' => 37.9376,
                'longitude' => 41.9376,
                'total_capacity' => 250,
                'phone' => '0484 123 45 67',
                'description' => 'Siirt’in popüler sineması.',
            ],
            [
                'city_id' => 56,
                'name' => 'Cinemaximum Siirt Merkez',
                'address' => 'Merkez, Siirt',
                'latitude' => 37.9354,
                'longitude' => 41.9354,
                'total_capacity' => 230,
                'phone' => '0484 543 21 09',
                'description' => 'Siirt’in yeni sineması.',
            ],
            [
                'city_id' => 57,
                'name' => 'Sinop Cinemaximum Merkez',
                'address' => 'Merkez, Sinop',
                'latitude' => 42.0276,
                'longitude' => 35.1576,
                'total_capacity' => 300,
                'phone' => '0368 987 65 43',
                'description' => 'Sinop’un popüler sineması.',
            ],
            [
                'city_id' => 57,
                'name' => 'Cinemaximum Boyabat',
                'address' => 'Boyabat, Sinop',
                'latitude' => 41.4876,
                'longitude' => 34.2876,
                'total_capacity' => 280,
                'phone' => '0368 321 09 87',
                'description' => 'Sinop’un Boyabat ilçesindeki sineması.',
            ],
            [
                'city_id' => 58,
                'name' => 'Sivas Primemall Cinemaximum',
                'address' => 'Primemall AVM, Sivas',
                'latitude' => 39.7576,
                'longitude' => 37.0176,
                'total_capacity' => 350,
                'phone' => '0346 123 45 67',
                'description' => 'Sivas’ın popüler sineması.',
            ],
            [
                'city_id' => 58,
                'name' => 'Cinemaximum Sivas Merkez',
                'address' => 'Merkez, Sivas',
                'latitude' => 39.7554,
                'longitude' => 37.0154,
                'total_capacity' => 330,
                'phone' => '0346 543 21 09',
                'description' => 'Sivas’ın yeni sineması.',
            ],
            [
                'city_id' => 59,
                'name' => 'Tekirdağ Tekira Cinemaximum',
                'address' => 'Tekira AVM, Tekirdağ',
                'latitude' => 40.9776,
                'longitude' => 27.5176,
                'total_capacity' => 380,
                'phone' => '0282 987 65 43',
                'description' => 'Tekirdağ’ın popüler sineması.',
            ],
            [
                'city_id' => 59,
                'name' => 'Cinemaximum Çorlu',
                'address' => 'Çorlu, Tekirdağ',
                'latitude' => 41.1576,
                'longitude' => 27.8076,
                'total_capacity' => 360,
                'phone' => '0282 321 09 87',
                'description' => 'Tekirdağ’ın Çorlu ilçesindeki sineması.',
            ],
            [
                'city_id' => 60,
                'name' => 'Tokat Novada Cinemaximum',
                'address' => 'Novada AVM, Tokat',
                'latitude' => 40.3276,
                'longitude' => 36.5576,
                'total_capacity' => 320,
                'phone' => '0356 123 45 67',
                'description' => 'Tokat’ın popüler sineması.',
            ],
            [
                'city_id' => 60,
                'name' => 'Cinemaximum Tokat Merkez',
                'address' => 'Merkez, Tokat',
                'latitude' => 40.3254,
                'longitude' => 36.5554,
                'total_capacity' => 300,
                'phone' => '0356 543 21 09',
                'description' => 'Tokat’ın yeni sineması.',
            ],
            [
                'city_id' => 61,
                'name' => 'Trabzon Forum Cinemaximum',
                'address' => 'Forum AVM, Trabzon',
                'latitude' => 41.0076,
                'longitude' => 39.7176,
                'total_capacity' => 400,
                'phone' => '0462 987 65 43',
                'description' => 'Trabzon’un popüler sinemalarından.',
            ],
            [
                'city_id' => 61,
                'name' => 'Cinemaximum Cevahir Trabzon',
                'address' => 'Cevahir AVM, Trabzon',
                'latitude' => 41.0054,
                'longitude' => 39.7154,
                'total_capacity' => 380,
                'phone' => '0462 321 09 87',
                'description' => 'Trabzon’un modern sineması.',
            ],
            [
                'city_id' => 62,
                'name' => 'Tunceli Cinemaximum Merkez',
                'address' => 'Merkez, Tunceli',
                'latitude' => 39.1076,
                'longitude' => 39.5376,
                'total_capacity' => 250,
                'phone' => '0428 123 45 67',
                'description' => 'Tunceli’nin popüler sineması.',
            ],
            [
                'city_id' => 62,
                'name' => 'Cinemaximum Pertek',
                'address' => 'Pertek, Tunceli',
                'latitude' => 38.8376,
                'longitude' => 39.1176,
                'total_capacity' => 230,
                'phone' => '0428 543 21 09',
                'description' => 'Tunceli’nin Pertek ilçesindeki sineması.',
            ],
            [
                'city_id' => 63,
                'name' => 'Şanlıurfa Piazza Cinemaximum',
                'address' => 'Piazza AVM, Şanlıurfa',
                'latitude' => 37.1576,
                'longitude' => 38.7876,
                'total_capacity' => 420,
                'phone' => '0414 987 65 43',
                'description' => 'Şanlıurfa’nın popüler sinemalarından.',
            ],
            [
                'city_id' => 63,
                'name' => 'Cinemaximum Urfa City',
                'address' => 'Urfa City AVM, Şanlıurfa',
                'latitude' => 37.1554,
                'longitude' => 38.7854,
                'total_capacity' => 400,
                'phone' => '0414 321 09 87',
                'description' => 'Şanlıurfa’nın modern sineması.',
            ],
            [
                'city_id' => 64,
                'name' => 'Uşak Cinemaximum Merkez',
                'address' => 'Merkez, Uşak',
                'latitude' => 38.6776,
                'longitude' => 29.4176,
                'total_capacity' => 330,
                'phone' => '0276 123 45 67',
                'description' => 'Uşak’ın popüler sineması.',
            ],
            [
                'city_id' => 64,
                'name' => 'Cinemaximum Egem Park',
                'address' => 'Egem Park AVM, Uşak',
                'latitude' => 38.6754,
                'longitude' => 29.4154,
                'total_capacity' => 310,
                'phone' => '0276 543 21 09',
                'description' => 'Uşak’ın yeni sineması.',
            ],
            [
                'city_id' => 65,
                'name' => 'Van AVM Cinemaximum',
                'address' => 'AVM, Van',
                'latitude' => 38.5076,
                'longitude' => 43.3776,
                'total_capacity' => 380,
                'phone' => '0432 987 65 43',
                'description' => 'Van’ın popüler sinemalarından.',
            ],
            [
                'city_id' => 65,
                'name' => 'Cinemaximum Van Merkez',
                'address' => 'Merkez, Van',
                'latitude' => 38.5054,
                'longitude' => 43.3754,
                'total_capacity' => 360,
                'phone' => '0432 321 09 87',
                'description' => 'Van’ın modern sineması.',
            ],
            [
                'city_id' => 66,
                'name' => 'Yozgat Novada Cinemaximum',
                'address' => 'Novada AVM, Yozgat',
                'latitude' => 39.8176,
                'longitude' => 34.8076,
                'total_capacity' => 320,
                'phone' => '0354 123 45 67',
                'description' => 'Yozgat’ın popüler sineması.',
            ],
            [
                'city_id' => 66,
                'name' => 'Cinemaximum Yozgat Merkez',
                'address' => 'Merkez, Yozgat',
                'latitude' => 39.8154,
                'longitude' => 34.8054,
                'total_capacity' => 300,
                'phone' => '0354 543 21 09',
                'description' => 'Yozgat’ın yeni sineması.',
            ],
            [
                'city_id' => 67,
                'name' => 'Zonguldak Demirpark Cinemaximum',
                'address' => 'Demirpark AVM, Zonguldak',
                'latitude' => 41.4576,
                'longitude' => 31.7876,
                'total_capacity' => 350,
                'phone' => '0372 987 65 43',
                'description' => 'Zonguldak’ın popüler sineması.',
            ],
            [
                'city_id' => 67,
                'name' => 'Cinemaximum Ereğli',
                'address' => 'Ereğli, Zonguldak',
                'latitude' => 41.2876,
                'longitude' => 31.4176,
                'total_capacity' => 330,
                'phone' => '0372 321 09 87',
                'description' => 'Zonguldak’ın Ereğli ilçesindeki sineması.',
            ],
            [
                'city_id' => 68,
                'name' => 'Aksaray Park Site Cinemaximum',
                'address' => 'Park Site AVM, Aksaray',
                'latitude' => 38.3776,
                'longitude' => 34.0276,
                'total_capacity' => 300,
                'phone' => '0382 123 45 67',
                'description' => 'Aksaray’ın popüler sineması.',
            ],
            [
                'city_id' => 68,
                'name' => 'Cinemaximum Aksaray Merkez',
                'address' => 'Merkez, Aksaray',
                'latitude' => 38.3754,
                'longitude' => 34.0254,
                'total_capacity' => 280,
                'phone' => '0382 543 21 09',
                'description' => 'Aksaray’ın yeni sineması.',
            ],
            [
                'city_id' => 69,
                'name' => 'Bayburt Cinemaximum Merkez',
                'address' => 'Merkez, Bayburt',
                'latitude' => 40.2576,
                'longitude' => 40.2276,
                'total_capacity' => 250,
                'phone' => '0458 987 65 43',
                'description' => 'Bayburt’un popüler sineması.',
            ],
            [
                'city_id' => 69,
                'name' => 'Cinemaximum Demirözü',
                'address' => 'Demirözü, Bayburt',
                'latitude' => 40.1076,
                'longitude' => 40.1076,
                'total_capacity' => 230,
                'phone' => '0458 321 09 87',
                'description' => 'Bayburt’un Demirözü ilçesindeki sineması.',
            ],
            [
                'city_id' => 70,
                'name' => 'Karaman Park AVM Cinemaximum',
                'address' => 'Park AVM, Karaman',
                'latitude' => 37.1876,
                'longitude' => 33.2276,
                'total_capacity' => 330,
                'phone' => '0338 123 45 67',
                'description' => 'Karaman’ın popüler sineması.',
            ],
            [
                'city_id' => 70,
                'name' => 'Cinemaximum Karaman Merkez',
                'address' => 'Merkez, Karaman',
                'latitude' => 37.1854,
                'longitude' => 33.2254,
                'total_capacity' => 310,
                'phone' => '0338 543 21 09',
                'description' => 'Karaman’ın yeni sineması.',
            ],
            [
                'city_id' => 71,
                'name' => 'Kırıkkale Podium Cinemaximum',
                'address' => 'Podium AVM, Kırıkkale',
                'latitude' => 39.8476,
                'longitude' => 33.5176,
                'total_capacity' => 350,
                'phone' => '0318 987 65 43',
                'description' => 'Kırıkkale’nin popüler sineması.',
            ],
            [
                'city_id' => 71,
                'name' => 'Cinemaximum Kırıkkale Merkez',
                'address' => 'Merkez, Kırıkkale',
                'latitude' => 39.8454,
                'longitude' => 33.5154,
                'total_capacity' => 330,
                'phone' => '0318 321 09 87',
                'description' => 'Kırıkkale’nin yeni sineması.',
            ],
            [
                'city_id' => 72,
                'name' => 'Batman Park AVM Cinemaximum',
                'address' => 'Park AVM, Batman',
                'latitude' => 37.8976,
                'longitude' => 41.1376,
                'total_capacity' => 380,
                'phone' => '0488 123 45 67',
                'description' => 'Batman’ın popüler sineması.',
            ],
            [
                'city_id' => 72,
                'name' => 'Cinemaximum Batman Merkez',
                'address' => 'Merkez, Batman',
                'latitude' => 37.8954,
                'longitude' => 41.1354,
                'total_capacity' => 360,
                'phone' => '0488 543 21 09',
                'description' => 'Batman’ın yeni sineması.',
            ],
            [
                'city_id' => 73,
                'name' => 'Şırnak Park AVM Cinemaximum',
                'address' => 'Park AVM, Şırnak',
                'latitude' => 37.5276,
                'longitude' => 42.4576,
                'total_capacity' => 280,
                'phone' => '0486 987 65 43',
                'description' => 'Şırnak’ın popüler sineması.',
            ],
            [
                'city_id' => 73,
                'name' => 'Cinemaximum Cizre',
                'address' => 'Cizre, Şırnak',
                'latitude' => 37.3176,
                'longitude' => 42.1876,
                'total_capacity' => 260,
                'phone' => '0486 321 09 87',
                'description' => 'Şırnak’ın Cizre ilçesindeki sineması.',
            ],
            [
                'city_id' => 74,
                'name' => 'Bartın Cinemaximum Merkez',
                'address' => 'Merkez, Bartın',
                'latitude' => 41.6376,
                'longitude' => 32.3376,
                'total_capacity' => 300,
                'phone' => '0378 123 45 67',
                'description' => 'Bartın’ın popüler sineması.',
            ],
            [
                'city_id' => 74,
                'name' => 'Cinemaximum Amasra',
                'address' => 'Amasra, Bartın',
                'latitude' => 41.7476,
                'longitude' => 32.3876,
                'total_capacity' => 280,
                'phone' => '0378 543 21 09',
                'description' => 'Bartın’ın Amasra ilçesindeki sineması.',
            ],
            [
                'city_id' => 75,
                'name' => 'Ardahan Cinemaximum Merkez',
                'address' => 'Merkez, Ardahan',
                'latitude' => 41.1176,
                'longitude' => 42.7076,
                'total_capacity' => 250,
                'phone' => '0478 987 65 43',
                'description' => 'Ardahan’ın popüler sineması.',
            ],
            [
                'city_id' => 75,
                'name' => 'Cinemaximum Göle',
                'address' => 'Göle, Ardahan',
                'latitude' => 40.7576,
                'longitude' => 42.5276,
                'total_capacity' => 230,
                'phone' => '0478 321 09 87',
                'description' => 'Ardahan’ın Göle ilçesindeki sineması.',
            ],
            [
                'city_id' => 76,
                'name' => 'Iğdır Cinemaximum Merkez',
                'address' => 'Merkez, Iğdır',
                'latitude' => 39.9276,
                'longitude' => 44.0476,
                'total_capacity' => 330,
                'phone' => '0476 123 45 67',
                'description' => 'Iğdır’ın popüler sineması.',
            ],
            [
                'city_id' => 76,
                'name' => 'Cinemaximum Tuzluca',
                'address' => 'Tuzluca, Iğdır',
                'latitude' => 40.0176,
                'longitude' => 43.8376,
                'total_capacity' => 310,
                'phone' => '0476 543 21 09',
                'description' => 'Iğdır’ın Tuzluca ilçesindeki sineması.',
            ],
            [
                'city_id' => 77,
                'name' => 'Yalova Cinemaximum Merkez',
                'address' => 'Merkez, Yalova',
                'latitude' => 40.6576,
                'longitude' => 29.2776,
                'total_capacity' => 350,
                'phone' => '0226 987 65 43',
                'description' => 'Yalova’nın popüler sineması.',
            ],
            [
                'city_id' => 77,
                'name' => 'Cinemaximum Çiftlikköy',
                'address' => 'Çiftlikköy, Yalova',
                'latitude' => 40.6376,
                'longitude' => 29.3576,
                'total_capacity' => 330,
                'phone' => '0226 321 09 87',
                'description' => 'Yalova’nın Çiftlikköy ilçesindeki sineması.',
            ],
            [
                'city_id' => 78,
                'name' => 'Karabük Cinemaximum Merkez',
                'address' => 'Merkez, Karabük',
                'latitude' => 41.2076,
                'longitude' => 32.6276,
                'total_capacity' => 380,
                'phone' => '0370 123 45 67',
                'description' => 'Karabük’ün popüler sineması.',
            ],
            [
                'city_id' => 78,
                'name' => 'Cinemaximum Safranbolu',
                'address' => 'Safranbolu, Karabük',
                'latitude' => 41.2576,
                'longitude' => 32.6876,
                'total_capacity' => 360,
                'phone' => '0370 543 21 09',
                'description' => 'Karabük’ün Safranbolu ilçesindeki sineması.',
            ],
            [
                'city_id' => 79,
                'name' => 'Kilis Cinemaximum Merkez',
                'address' => 'Merkez, Kilis',
                'latitude' => 36.7176,
                'longitude' => 37.1176,
                'total_capacity' => 280,
                'phone' => '0348 987 65 43',
                'description' => 'Kilis’in popüler sineması.',
            ],
            [
                'city_id' => 79,
                'name' => 'Cinemaximum Elbeyli',
                'address' => 'Elbeyli, Kilis',
                'latitude' => 36.9076,
                'longitude' => 37.2876,
                'total_capacity' => 260,
                'phone' => '0348 321 09 87',
                'description' => 'Kilis’in Elbeyli ilçesindeki sineması.',
            ],
            [
                'city_id' => 80,
                'name' => 'Osmaniye Park 328 Cinemaximum',
                'address' => 'Park 328 AVM, Osmaniye',
                'latitude' => 37.0776,
                'longitude' => 36.2476,
                'total_capacity' => 330,
                'phone' => '0328 123 45 67',
                'description' => 'Osmaniye’nin popüler sineması.',
            ],
            [
                'city_id' => 80,
                'name' => 'Cinemaximum Kadirli',
                'address' => 'Kadirli, Osmaniye',
                'latitude' => 37.3876,
                'longitude' => 36.1076,
                'total_capacity' => 310,
                'phone' => '0328 543 21 09',
                'description' => 'Osmaniye’nin Kadirli ilçesindeki sineması.',
            ],
            [
                'city_id' => 81,
                'name' => 'Düzce Krempark Cinemaximum',
                'address' => 'Krempark AVM, Düzce',
                'latitude' => 40.8476,
                'longitude' => 31.1576,
                'total_capacity' => 360,
                'phone' => '0380 987 65 43',
                'description' => 'Düzce’nin popüler sineması.',
            ],
            [
                'city_id' => 81,
                'name' => 'Cinemaximum Düzce Merkez',
                'address' => 'Merkez, Düzce',
                'latitude' => 40.8454,
                'longitude' => 31.1554,
                'total_capacity' => 340,
                'phone' => '0380 321 09 87',
                'description' => 'Düzce’nin yeni sineması.',
            ],


          
        ];

        foreach ($cinemas as $cinema) {
            Cinema::create($cinema);
        }
    }
}
